// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.dingodb.pb.raft;

public interface PutIfAbsentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.raft.PutIfAbsentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes put_keys = 1 [json_name = "putKeys"];</code>
   * @return A list containing the putKeys.
   */
  java.util.List<com.google.protobuf.ByteString> getPutKeysList();
  /**
   * <code>repeated bytes put_keys = 1 [json_name = "putKeys"];</code>
   * @return The count of putKeys.
   */
  int getPutKeysCount();
  /**
   * <code>repeated bytes put_keys = 1 [json_name = "putKeys"];</code>
   * @param index The index of the element to return.
   * @return The putKeys at the given index.
   */
  com.google.protobuf.ByteString getPutKeys(int index);
}
