// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.dingodb.pb.raft;

public interface PutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.raft.PutResponse)
    com.google.protobuf.MessageOrBuilder {
}
