// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.dingodb.pb.raft;

public interface RaftCmdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.raft.RaftCmdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.raft.ResponseHeader header = 1 [json_name = "header"];</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.dingodb.pb.raft.ResponseHeader header = 1 [json_name = "header"];</code>
   * @return The header.
   */
  com.dingodb.pb.raft.ResponseHeader getHeader();
  /**
   * <code>.dingodb.pb.raft.ResponseHeader header = 1 [json_name = "header"];</code>
   */
  com.dingodb.pb.raft.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .dingodb.pb.raft.Response responses = 2 [json_name = "responses"];</code>
   */
  java.util.List<com.dingodb.pb.raft.Response> 
      getResponsesList();
  /**
   * <code>repeated .dingodb.pb.raft.Response responses = 2 [json_name = "responses"];</code>
   */
  com.dingodb.pb.raft.Response getResponses(int index);
  /**
   * <code>repeated .dingodb.pb.raft.Response responses = 2 [json_name = "responses"];</code>
   */
  int getResponsesCount();
  /**
   * <code>repeated .dingodb.pb.raft.Response responses = 2 [json_name = "responses"];</code>
   */
  java.util.List<? extends com.dingodb.pb.raft.ResponseOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <code>repeated .dingodb.pb.raft.Response responses = 2 [json_name = "responses"];</code>
   */
  com.dingodb.pb.raft.ResponseOrBuilder getResponsesOrBuilder(
      int index);
}
