// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.dingodb.pb.raft;

public interface RequestHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.raft.RequestHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 region_id = 1 [json_name = "regionId"];</code>
   * @return The regionId.
   */
  long getRegionId();
}
