// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.dingodb.pb.common;

public interface KeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.common.KeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
