// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.dingodb.pb.common;

public interface StoreMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.common.StoreMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 epoch = 1 [json_name = "epoch"];</code>
   * @return The epoch.
   */
  long getEpoch();

  /**
   * <code>repeated .dingodb.pb.common.Store stores = 2 [json_name = "stores"];</code>
   */
  java.util.List<com.dingodb.pb.common.Store> 
      getStoresList();
  /**
   * <code>repeated .dingodb.pb.common.Store stores = 2 [json_name = "stores"];</code>
   */
  com.dingodb.pb.common.Store getStores(int index);
  /**
   * <code>repeated .dingodb.pb.common.Store stores = 2 [json_name = "stores"];</code>
   */
  int getStoresCount();
  /**
   * <code>repeated .dingodb.pb.common.Store stores = 2 [json_name = "stores"];</code>
   */
  java.util.List<? extends com.dingodb.pb.common.StoreOrBuilder> 
      getStoresOrBuilderList();
  /**
   * <code>repeated .dingodb.pb.common.Store stores = 2 [json_name = "stores"];</code>
   */
  com.dingodb.pb.common.StoreOrBuilder getStoresOrBuilder(
      int index);
}
