// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package com.dingodb.pb.coordinator;

public interface CreateStoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.coordinator.CreateStoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 cluster_id = 1 [json_name = "clusterId"];</code>
   * @return The clusterId.
   */
  long getClusterId();
}
