// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package com.dingodb.pb.coordinator;

public interface StoreHeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.coordinator.StoreHeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  com.dingodb.pb.error.Error getError();
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   */
  com.dingodb.pb.error.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * the lates epoch of storemap
   * </pre>
   *
   * <code>uint64 storemap_epoch = 2 [json_name = "storemapEpoch"];</code>
   * @return The storemapEpoch.
   */
  long getStoremapEpoch();

  /**
   * <pre>
   * the lates epoch of regionmap
   * </pre>
   *
   * <code>uint64 regionmap_epoch = 3 [json_name = "regionmapEpoch"];</code>
   * @return The regionmapEpoch.
   */
  long getRegionmapEpoch();

  /**
   * <pre>
   * new storemap
   * </pre>
   *
   * <code>.dingodb.pb.common.StoreMap storemap = 4 [json_name = "storemap"];</code>
   * @return Whether the storemap field is set.
   */
  boolean hasStoremap();
  /**
   * <pre>
   * new storemap
   * </pre>
   *
   * <code>.dingodb.pb.common.StoreMap storemap = 4 [json_name = "storemap"];</code>
   * @return The storemap.
   */
  com.dingodb.pb.common.StoreMap getStoremap();
  /**
   * <pre>
   * new storemap
   * </pre>
   *
   * <code>.dingodb.pb.common.StoreMap storemap = 4 [json_name = "storemap"];</code>
   */
  com.dingodb.pb.common.StoreMapOrBuilder getStoremapOrBuilder();

  /**
   * <pre>
   * new regionmap
   * </pre>
   *
   * <code>.dingodb.pb.common.RegionMap regionmap = 5 [json_name = "regionmap"];</code>
   * @return Whether the regionmap field is set.
   */
  boolean hasRegionmap();
  /**
   * <pre>
   * new regionmap
   * </pre>
   *
   * <code>.dingodb.pb.common.RegionMap regionmap = 5 [json_name = "regionmap"];</code>
   * @return The regionmap.
   */
  com.dingodb.pb.common.RegionMap getRegionmap();
  /**
   * <pre>
   * new regionmap
   * </pre>
   *
   * <code>.dingodb.pb.common.RegionMap regionmap = 5 [json_name = "regionmap"];</code>
   */
  com.dingodb.pb.common.RegionMapOrBuilder getRegionmapOrBuilder();
}
