// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

/**
 * Protobuf type {@code dingodb.pb.meta.CreateSchemaRequest}
 */
public final class CreateSchemaRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.meta.CreateSchemaRequest)
    CreateSchemaRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateSchemaRequest.newBuilder() to construct.
  private CreateSchemaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateSchemaRequest() {
    schemaName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateSchemaRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateSchemaRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateSchemaRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.meta.CreateSchemaRequest.class, com.dingodb.pb.meta.CreateSchemaRequest.Builder.class);
  }

  public static final int PARENT_SCHEMA_ID_FIELD_NUMBER = 1;
  private com.dingodb.pb.meta.DingoCommonId parentSchemaId_;
  /**
   * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
   * @return Whether the parentSchemaId field is set.
   */
  @java.lang.Override
  public boolean hasParentSchemaId() {
    return parentSchemaId_ != null;
  }
  /**
   * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
   * @return The parentSchemaId.
   */
  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonId getParentSchemaId() {
    return parentSchemaId_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : parentSchemaId_;
  }
  /**
   * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonIdOrBuilder getParentSchemaIdOrBuilder() {
    return parentSchemaId_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : parentSchemaId_;
  }

  public static final int SCHEMA_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object schemaName_ = "";
  /**
   * <code>string schema_name = 2 [json_name = "schemaName"];</code>
   * @return The schemaName.
   */
  @java.lang.Override
  public java.lang.String getSchemaName() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaName_ = s;
      return s;
    }
  }
  /**
   * <code>string schema_name = 2 [json_name = "schemaName"];</code>
   * @return The bytes for schemaName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaNameBytes() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (parentSchemaId_ != null) {
      output.writeMessage(1, getParentSchemaId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, schemaName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (parentSchemaId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getParentSchemaId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, schemaName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.meta.CreateSchemaRequest)) {
      return super.equals(obj);
    }
    com.dingodb.pb.meta.CreateSchemaRequest other = (com.dingodb.pb.meta.CreateSchemaRequest) obj;

    if (hasParentSchemaId() != other.hasParentSchemaId()) return false;
    if (hasParentSchemaId()) {
      if (!getParentSchemaId()
          .equals(other.getParentSchemaId())) return false;
    }
    if (!getSchemaName()
        .equals(other.getSchemaName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasParentSchemaId()) {
      hash = (37 * hash) + PARENT_SCHEMA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getParentSchemaId().hashCode();
    }
    hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.CreateSchemaRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.meta.CreateSchemaRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dingodb.pb.meta.CreateSchemaRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.meta.CreateSchemaRequest)
      com.dingodb.pb.meta.CreateSchemaRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateSchemaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateSchemaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.meta.CreateSchemaRequest.class, com.dingodb.pb.meta.CreateSchemaRequest.Builder.class);
    }

    // Construct using com.dingodb.pb.meta.CreateSchemaRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      parentSchemaId_ = null;
      if (parentSchemaIdBuilder_ != null) {
        parentSchemaIdBuilder_.dispose();
        parentSchemaIdBuilder_ = null;
      }
      schemaName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateSchemaRequest_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.CreateSchemaRequest getDefaultInstanceForType() {
      return com.dingodb.pb.meta.CreateSchemaRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.meta.CreateSchemaRequest build() {
      com.dingodb.pb.meta.CreateSchemaRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.CreateSchemaRequest buildPartial() {
      com.dingodb.pb.meta.CreateSchemaRequest result = new com.dingodb.pb.meta.CreateSchemaRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dingodb.pb.meta.CreateSchemaRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.parentSchemaId_ = parentSchemaIdBuilder_ == null
            ? parentSchemaId_
            : parentSchemaIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.schemaName_ = schemaName_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.meta.CreateSchemaRequest) {
        return mergeFrom((com.dingodb.pb.meta.CreateSchemaRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.meta.CreateSchemaRequest other) {
      if (other == com.dingodb.pb.meta.CreateSchemaRequest.getDefaultInstance()) return this;
      if (other.hasParentSchemaId()) {
        mergeParentSchemaId(other.getParentSchemaId());
      }
      if (!other.getSchemaName().isEmpty()) {
        schemaName_ = other.schemaName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getParentSchemaIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              schemaName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.dingodb.pb.meta.DingoCommonId parentSchemaId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder> parentSchemaIdBuilder_;
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     * @return Whether the parentSchemaId field is set.
     */
    public boolean hasParentSchemaId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     * @return The parentSchemaId.
     */
    public com.dingodb.pb.meta.DingoCommonId getParentSchemaId() {
      if (parentSchemaIdBuilder_ == null) {
        return parentSchemaId_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : parentSchemaId_;
      } else {
        return parentSchemaIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    public Builder setParentSchemaId(com.dingodb.pb.meta.DingoCommonId value) {
      if (parentSchemaIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parentSchemaId_ = value;
      } else {
        parentSchemaIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    public Builder setParentSchemaId(
        com.dingodb.pb.meta.DingoCommonId.Builder builderForValue) {
      if (parentSchemaIdBuilder_ == null) {
        parentSchemaId_ = builderForValue.build();
      } else {
        parentSchemaIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    public Builder mergeParentSchemaId(com.dingodb.pb.meta.DingoCommonId value) {
      if (parentSchemaIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          parentSchemaId_ != null &&
          parentSchemaId_ != com.dingodb.pb.meta.DingoCommonId.getDefaultInstance()) {
          getParentSchemaIdBuilder().mergeFrom(value);
        } else {
          parentSchemaId_ = value;
        }
      } else {
        parentSchemaIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    public Builder clearParentSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      parentSchemaId_ = null;
      if (parentSchemaIdBuilder_ != null) {
        parentSchemaIdBuilder_.dispose();
        parentSchemaIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    public com.dingodb.pb.meta.DingoCommonId.Builder getParentSchemaIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getParentSchemaIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    public com.dingodb.pb.meta.DingoCommonIdOrBuilder getParentSchemaIdOrBuilder() {
      if (parentSchemaIdBuilder_ != null) {
        return parentSchemaIdBuilder_.getMessageOrBuilder();
      } else {
        return parentSchemaId_ == null ?
            com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : parentSchemaId_;
      }
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId parent_schema_id = 1 [json_name = "parentSchemaId"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder> 
        getParentSchemaIdFieldBuilder() {
      if (parentSchemaIdBuilder_ == null) {
        parentSchemaIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder>(
                getParentSchemaId(),
                getParentForChildren(),
                isClean());
        parentSchemaId_ = null;
      }
      return parentSchemaIdBuilder_;
    }

    private java.lang.Object schemaName_ = "";
    /**
     * <code>string schema_name = 2 [json_name = "schemaName"];</code>
     * @return The schemaName.
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string schema_name = 2 [json_name = "schemaName"];</code>
     * @return The bytes for schemaName.
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string schema_name = 2 [json_name = "schemaName"];</code>
     * @param value The schemaName to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      schemaName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string schema_name = 2 [json_name = "schemaName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaName() {
      schemaName_ = getDefaultInstance().getSchemaName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string schema_name = 2 [json_name = "schemaName"];</code>
     * @param value The bytes for schemaName to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      schemaName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.meta.CreateSchemaRequest)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.meta.CreateSchemaRequest)
  private static final com.dingodb.pb.meta.CreateSchemaRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.meta.CreateSchemaRequest();
  }

  public static com.dingodb.pb.meta.CreateSchemaRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSchemaRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateSchemaRequest>() {
    @java.lang.Override
    public CreateSchemaRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateSchemaRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSchemaRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.meta.CreateSchemaRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

