// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

/**
 * Protobuf type {@code dingodb.pb.meta.CreateTableRequest}
 */
public final class CreateTableRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.meta.CreateTableRequest)
    CreateTableRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTableRequest.newBuilder() to construct.
  private CreateTableRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTableRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateTableRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateTableRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateTableRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.meta.CreateTableRequest.class, com.dingodb.pb.meta.CreateTableRequest.Builder.class);
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 1;
  private com.dingodb.pb.meta.DingoCommonId schemaId_;
  /**
   * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
   * @return Whether the schemaId field is set.
   */
  @java.lang.Override
  public boolean hasSchemaId() {
    return schemaId_ != null;
  }
  /**
   * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
   * @return The schemaId.
   */
  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonId getSchemaId() {
    return schemaId_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : schemaId_;
  }
  /**
   * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonIdOrBuilder getSchemaIdOrBuilder() {
    return schemaId_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : schemaId_;
  }

  public static final int TABLE_DEFINITION_FIELD_NUMBER = 2;
  private com.dingodb.pb.meta.TableDefinition tableDefinition_;
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   * @return Whether the tableDefinition field is set.
   */
  @java.lang.Override
  public boolean hasTableDefinition() {
    return tableDefinition_ != null;
  }
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   * @return The tableDefinition.
   */
  @java.lang.Override
  public com.dingodb.pb.meta.TableDefinition getTableDefinition() {
    return tableDefinition_ == null ? com.dingodb.pb.meta.TableDefinition.getDefaultInstance() : tableDefinition_;
  }
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.meta.TableDefinitionOrBuilder getTableDefinitionOrBuilder() {
    return tableDefinition_ == null ? com.dingodb.pb.meta.TableDefinition.getDefaultInstance() : tableDefinition_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schemaId_ != null) {
      output.writeMessage(1, getSchemaId());
    }
    if (tableDefinition_ != null) {
      output.writeMessage(2, getTableDefinition());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schemaId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSchemaId());
    }
    if (tableDefinition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTableDefinition());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.meta.CreateTableRequest)) {
      return super.equals(obj);
    }
    com.dingodb.pb.meta.CreateTableRequest other = (com.dingodb.pb.meta.CreateTableRequest) obj;

    if (hasSchemaId() != other.hasSchemaId()) return false;
    if (hasSchemaId()) {
      if (!getSchemaId()
          .equals(other.getSchemaId())) return false;
    }
    if (hasTableDefinition() != other.hasTableDefinition()) return false;
    if (hasTableDefinition()) {
      if (!getTableDefinition()
          .equals(other.getTableDefinition())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSchemaId()) {
      hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaId().hashCode();
    }
    if (hasTableDefinition()) {
      hash = (37 * hash) + TABLE_DEFINITION_FIELD_NUMBER;
      hash = (53 * hash) + getTableDefinition().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.CreateTableRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.meta.CreateTableRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dingodb.pb.meta.CreateTableRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.meta.CreateTableRequest)
      com.dingodb.pb.meta.CreateTableRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateTableRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateTableRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.meta.CreateTableRequest.class, com.dingodb.pb.meta.CreateTableRequest.Builder.class);
    }

    // Construct using com.dingodb.pb.meta.CreateTableRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      schemaId_ = null;
      if (schemaIdBuilder_ != null) {
        schemaIdBuilder_.dispose();
        schemaIdBuilder_ = null;
      }
      tableDefinition_ = null;
      if (tableDefinitionBuilder_ != null) {
        tableDefinitionBuilder_.dispose();
        tableDefinitionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_CreateTableRequest_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.CreateTableRequest getDefaultInstanceForType() {
      return com.dingodb.pb.meta.CreateTableRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.meta.CreateTableRequest build() {
      com.dingodb.pb.meta.CreateTableRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.CreateTableRequest buildPartial() {
      com.dingodb.pb.meta.CreateTableRequest result = new com.dingodb.pb.meta.CreateTableRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dingodb.pb.meta.CreateTableRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schemaId_ = schemaIdBuilder_ == null
            ? schemaId_
            : schemaIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tableDefinition_ = tableDefinitionBuilder_ == null
            ? tableDefinition_
            : tableDefinitionBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.meta.CreateTableRequest) {
        return mergeFrom((com.dingodb.pb.meta.CreateTableRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.meta.CreateTableRequest other) {
      if (other == com.dingodb.pb.meta.CreateTableRequest.getDefaultInstance()) return this;
      if (other.hasSchemaId()) {
        mergeSchemaId(other.getSchemaId());
      }
      if (other.hasTableDefinition()) {
        mergeTableDefinition(other.getTableDefinition());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSchemaIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTableDefinitionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.dingodb.pb.meta.DingoCommonId schemaId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder> schemaIdBuilder_;
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     * @return Whether the schemaId field is set.
     */
    public boolean hasSchemaId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     * @return The schemaId.
     */
    public com.dingodb.pb.meta.DingoCommonId getSchemaId() {
      if (schemaIdBuilder_ == null) {
        return schemaId_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : schemaId_;
      } else {
        return schemaIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    public Builder setSchemaId(com.dingodb.pb.meta.DingoCommonId value) {
      if (schemaIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schemaId_ = value;
      } else {
        schemaIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    public Builder setSchemaId(
        com.dingodb.pb.meta.DingoCommonId.Builder builderForValue) {
      if (schemaIdBuilder_ == null) {
        schemaId_ = builderForValue.build();
      } else {
        schemaIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    public Builder mergeSchemaId(com.dingodb.pb.meta.DingoCommonId value) {
      if (schemaIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          schemaId_ != null &&
          schemaId_ != com.dingodb.pb.meta.DingoCommonId.getDefaultInstance()) {
          getSchemaIdBuilder().mergeFrom(value);
        } else {
          schemaId_ = value;
        }
      } else {
        schemaIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    public Builder clearSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      schemaId_ = null;
      if (schemaIdBuilder_ != null) {
        schemaIdBuilder_.dispose();
        schemaIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    public com.dingodb.pb.meta.DingoCommonId.Builder getSchemaIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSchemaIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    public com.dingodb.pb.meta.DingoCommonIdOrBuilder getSchemaIdOrBuilder() {
      if (schemaIdBuilder_ != null) {
        return schemaIdBuilder_.getMessageOrBuilder();
      } else {
        return schemaId_ == null ?
            com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : schemaId_;
      }
    }
    /**
     * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder> 
        getSchemaIdFieldBuilder() {
      if (schemaIdBuilder_ == null) {
        schemaIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder>(
                getSchemaId(),
                getParentForChildren(),
                isClean());
        schemaId_ = null;
      }
      return schemaIdBuilder_;
    }

    private com.dingodb.pb.meta.TableDefinition tableDefinition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.TableDefinition, com.dingodb.pb.meta.TableDefinition.Builder, com.dingodb.pb.meta.TableDefinitionOrBuilder> tableDefinitionBuilder_;
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     * @return Whether the tableDefinition field is set.
     */
    public boolean hasTableDefinition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     * @return The tableDefinition.
     */
    public com.dingodb.pb.meta.TableDefinition getTableDefinition() {
      if (tableDefinitionBuilder_ == null) {
        return tableDefinition_ == null ? com.dingodb.pb.meta.TableDefinition.getDefaultInstance() : tableDefinition_;
      } else {
        return tableDefinitionBuilder_.getMessage();
      }
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    public Builder setTableDefinition(com.dingodb.pb.meta.TableDefinition value) {
      if (tableDefinitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tableDefinition_ = value;
      } else {
        tableDefinitionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    public Builder setTableDefinition(
        com.dingodb.pb.meta.TableDefinition.Builder builderForValue) {
      if (tableDefinitionBuilder_ == null) {
        tableDefinition_ = builderForValue.build();
      } else {
        tableDefinitionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    public Builder mergeTableDefinition(com.dingodb.pb.meta.TableDefinition value) {
      if (tableDefinitionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          tableDefinition_ != null &&
          tableDefinition_ != com.dingodb.pb.meta.TableDefinition.getDefaultInstance()) {
          getTableDefinitionBuilder().mergeFrom(value);
        } else {
          tableDefinition_ = value;
        }
      } else {
        tableDefinitionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    public Builder clearTableDefinition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tableDefinition_ = null;
      if (tableDefinitionBuilder_ != null) {
        tableDefinitionBuilder_.dispose();
        tableDefinitionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    public com.dingodb.pb.meta.TableDefinition.Builder getTableDefinitionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTableDefinitionFieldBuilder().getBuilder();
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    public com.dingodb.pb.meta.TableDefinitionOrBuilder getTableDefinitionOrBuilder() {
      if (tableDefinitionBuilder_ != null) {
        return tableDefinitionBuilder_.getMessageOrBuilder();
      } else {
        return tableDefinition_ == null ?
            com.dingodb.pb.meta.TableDefinition.getDefaultInstance() : tableDefinition_;
      }
    }
    /**
     * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.TableDefinition, com.dingodb.pb.meta.TableDefinition.Builder, com.dingodb.pb.meta.TableDefinitionOrBuilder> 
        getTableDefinitionFieldBuilder() {
      if (tableDefinitionBuilder_ == null) {
        tableDefinitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.meta.TableDefinition, com.dingodb.pb.meta.TableDefinition.Builder, com.dingodb.pb.meta.TableDefinitionOrBuilder>(
                getTableDefinition(),
                getParentForChildren(),
                isClean());
        tableDefinition_ = null;
      }
      return tableDefinitionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.meta.CreateTableRequest)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.meta.CreateTableRequest)
  private static final com.dingodb.pb.meta.CreateTableRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.meta.CreateTableRequest();
  }

  public static com.dingodb.pb.meta.CreateTableRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTableRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateTableRequest>() {
    @java.lang.Override
    public CreateTableRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTableRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTableRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.meta.CreateTableRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

