// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

public interface CreateTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.meta.CreateTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
   * @return Whether the schemaId field is set.
   */
  boolean hasSchemaId();
  /**
   * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
   * @return The schemaId.
   */
  com.dingodb.pb.meta.DingoCommonId getSchemaId();
  /**
   * <code>.dingodb.pb.meta.DingoCommonId schema_id = 1 [json_name = "schemaId"];</code>
   */
  com.dingodb.pb.meta.DingoCommonIdOrBuilder getSchemaIdOrBuilder();

  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   * @return Whether the tableDefinition field is set.
   */
  boolean hasTableDefinition();
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   * @return The tableDefinition.
   */
  com.dingodb.pb.meta.TableDefinition getTableDefinition();
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   */
  com.dingodb.pb.meta.TableDefinitionOrBuilder getTableDefinitionOrBuilder();
}
