// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

/**
 * <pre>
 * Used for transformation to SDK CommonId
 * </pre>
 *
 * Protobuf type {@code dingodb.pb.meta.DingoCommonId}
 */
public final class DingoCommonId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.meta.DingoCommonId)
    DingoCommonIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DingoCommonId.newBuilder() to construct.
  private DingoCommonId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DingoCommonId() {
    entityType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DingoCommonId();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_DingoCommonId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_DingoCommonId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.meta.DingoCommonId.class, com.dingodb.pb.meta.DingoCommonId.Builder.class);
  }

  public static final int ENTITY_TYPE_FIELD_NUMBER = 1;
  private int entityType_ = 0;
  /**
   * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
   * @return The enum numeric value on the wire for entityType.
   */
  @java.lang.Override public int getEntityTypeValue() {
    return entityType_;
  }
  /**
   * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
   * @return The entityType.
   */
  @java.lang.Override public com.dingodb.pb.meta.EntityType getEntityType() {
    com.dingodb.pb.meta.EntityType result = com.dingodb.pb.meta.EntityType.forNumber(entityType_);
    return result == null ? com.dingodb.pb.meta.EntityType.UNRECOGNIZED : result;
  }

  public static final int PARENT_ENTITY_ID_FIELD_NUMBER = 2;
  private long parentEntityId_ = 0L;
  /**
   * <pre>
   * if the entity is table, this field is its schema_id
   * </pre>
   *
   * <code>uint64 parent_entity_id = 2 [json_name = "parentEntityId"];</code>
   * @return The parentEntityId.
   */
  @java.lang.Override
  public long getParentEntityId() {
    return parentEntityId_;
  }

  public static final int ENTITY_ID_FIELD_NUMBER = 3;
  private long entityId_ = 0L;
  /**
   * <code>uint64 entity_id = 3 [json_name = "entityId"];</code>
   * @return The entityId.
   */
  @java.lang.Override
  public long getEntityId() {
    return entityId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (entityType_ != com.dingodb.pb.meta.EntityType.ENTITY_TYPE_SCHEMA.getNumber()) {
      output.writeEnum(1, entityType_);
    }
    if (parentEntityId_ != 0L) {
      output.writeUInt64(2, parentEntityId_);
    }
    if (entityId_ != 0L) {
      output.writeUInt64(3, entityId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (entityType_ != com.dingodb.pb.meta.EntityType.ENTITY_TYPE_SCHEMA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, entityType_);
    }
    if (parentEntityId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, parentEntityId_);
    }
    if (entityId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, entityId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.meta.DingoCommonId)) {
      return super.equals(obj);
    }
    com.dingodb.pb.meta.DingoCommonId other = (com.dingodb.pb.meta.DingoCommonId) obj;

    if (entityType_ != other.entityType_) return false;
    if (getParentEntityId()
        != other.getParentEntityId()) return false;
    if (getEntityId()
        != other.getEntityId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENTITY_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + entityType_;
    hash = (37 * hash) + PARENT_ENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParentEntityId());
    hash = (37 * hash) + ENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntityId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.DingoCommonId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.meta.DingoCommonId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Used for transformation to SDK CommonId
   * </pre>
   *
   * Protobuf type {@code dingodb.pb.meta.DingoCommonId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.meta.DingoCommonId)
      com.dingodb.pb.meta.DingoCommonIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_DingoCommonId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_DingoCommonId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.meta.DingoCommonId.class, com.dingodb.pb.meta.DingoCommonId.Builder.class);
    }

    // Construct using com.dingodb.pb.meta.DingoCommonId.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      entityType_ = 0;
      parentEntityId_ = 0L;
      entityId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_DingoCommonId_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.DingoCommonId getDefaultInstanceForType() {
      return com.dingodb.pb.meta.DingoCommonId.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.meta.DingoCommonId build() {
      com.dingodb.pb.meta.DingoCommonId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.DingoCommonId buildPartial() {
      com.dingodb.pb.meta.DingoCommonId result = new com.dingodb.pb.meta.DingoCommonId(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dingodb.pb.meta.DingoCommonId result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entityType_ = entityType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.parentEntityId_ = parentEntityId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.entityId_ = entityId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.meta.DingoCommonId) {
        return mergeFrom((com.dingodb.pb.meta.DingoCommonId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.meta.DingoCommonId other) {
      if (other == com.dingodb.pb.meta.DingoCommonId.getDefaultInstance()) return this;
      if (other.entityType_ != 0) {
        setEntityTypeValue(other.getEntityTypeValue());
      }
      if (other.getParentEntityId() != 0L) {
        setParentEntityId(other.getParentEntityId());
      }
      if (other.getEntityId() != 0L) {
        setEntityId(other.getEntityId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              entityType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              parentEntityId_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              entityId_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int entityType_ = 0;
    /**
     * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
     * @return The enum numeric value on the wire for entityType.
     */
    @java.lang.Override public int getEntityTypeValue() {
      return entityType_;
    }
    /**
     * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
     * @param value The enum numeric value on the wire for entityType to set.
     * @return This builder for chaining.
     */
    public Builder setEntityTypeValue(int value) {
      entityType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
     * @return The entityType.
     */
    @java.lang.Override
    public com.dingodb.pb.meta.EntityType getEntityType() {
      com.dingodb.pb.meta.EntityType result = com.dingodb.pb.meta.EntityType.forNumber(entityType_);
      return result == null ? com.dingodb.pb.meta.EntityType.UNRECOGNIZED : result;
    }
    /**
     * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
     * @param value The entityType to set.
     * @return This builder for chaining.
     */
    public Builder setEntityType(com.dingodb.pb.meta.EntityType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      entityType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.meta.EntityType entity_type = 1 [json_name = "entityType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      entityType_ = 0;
      onChanged();
      return this;
    }

    private long parentEntityId_ ;
    /**
     * <pre>
     * if the entity is table, this field is its schema_id
     * </pre>
     *
     * <code>uint64 parent_entity_id = 2 [json_name = "parentEntityId"];</code>
     * @return The parentEntityId.
     */
    @java.lang.Override
    public long getParentEntityId() {
      return parentEntityId_;
    }
    /**
     * <pre>
     * if the entity is table, this field is its schema_id
     * </pre>
     *
     * <code>uint64 parent_entity_id = 2 [json_name = "parentEntityId"];</code>
     * @param value The parentEntityId to set.
     * @return This builder for chaining.
     */
    public Builder setParentEntityId(long value) {

      parentEntityId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if the entity is table, this field is its schema_id
     * </pre>
     *
     * <code>uint64 parent_entity_id = 2 [json_name = "parentEntityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParentEntityId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      parentEntityId_ = 0L;
      onChanged();
      return this;
    }

    private long entityId_ ;
    /**
     * <code>uint64 entity_id = 3 [json_name = "entityId"];</code>
     * @return The entityId.
     */
    @java.lang.Override
    public long getEntityId() {
      return entityId_;
    }
    /**
     * <code>uint64 entity_id = 3 [json_name = "entityId"];</code>
     * @param value The entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityId(long value) {

      entityId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 entity_id = 3 [json_name = "entityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      entityId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.meta.DingoCommonId)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.meta.DingoCommonId)
  private static final com.dingodb.pb.meta.DingoCommonId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.meta.DingoCommonId();
  }

  public static com.dingodb.pb.meta.DingoCommonId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DingoCommonId>
      PARSER = new com.google.protobuf.AbstractParser<DingoCommonId>() {
    @java.lang.Override
    public DingoCommonId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DingoCommonId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DingoCommonId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

