// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

public interface DropTableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.meta.DropTableResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  com.dingodb.pb.error.Error getError();
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   */
  com.dingodb.pb.error.ErrorOrBuilder getErrorOrBuilder();
}
