// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

/**
 * Protobuf type {@code dingodb.pb.meta.GetSchemasResponse}
 */
public final class GetSchemasResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.meta.GetSchemasResponse)
    GetSchemasResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSchemasResponse.newBuilder() to construct.
  private GetSchemasResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSchemasResponse() {
    schemas_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSchemasResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_GetSchemasResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_GetSchemasResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.meta.GetSchemasResponse.class, com.dingodb.pb.meta.GetSchemasResponse.Builder.class);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private com.dingodb.pb.error.Error error_;
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public com.dingodb.pb.error.Error getError() {
    return error_ == null ? com.dingodb.pb.error.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.error.ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.dingodb.pb.error.Error.getDefaultInstance() : error_;
  }

  public static final int SCHEMAS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.dingodb.pb.meta.Schema> schemas_;
  /**
   * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dingodb.pb.meta.Schema> getSchemasList() {
    return schemas_;
  }
  /**
   * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dingodb.pb.meta.SchemaOrBuilder> 
      getSchemasOrBuilderList() {
    return schemas_;
  }
  /**
   * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
   */
  @java.lang.Override
  public int getSchemasCount() {
    return schemas_.size();
  }
  /**
   * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.meta.Schema getSchemas(int index) {
    return schemas_.get(index);
  }
  /**
   * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.meta.SchemaOrBuilder getSchemasOrBuilder(
      int index) {
    return schemas_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    for (int i = 0; i < schemas_.size(); i++) {
      output.writeMessage(2, schemas_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    for (int i = 0; i < schemas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, schemas_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.meta.GetSchemasResponse)) {
      return super.equals(obj);
    }
    com.dingodb.pb.meta.GetSchemasResponse other = (com.dingodb.pb.meta.GetSchemasResponse) obj;

    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getSchemasList()
        .equals(other.getSchemasList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (getSchemasCount() > 0) {
      hash = (37 * hash) + SCHEMAS_FIELD_NUMBER;
      hash = (53 * hash) + getSchemasList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.GetSchemasResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.meta.GetSchemasResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dingodb.pb.meta.GetSchemasResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.meta.GetSchemasResponse)
      com.dingodb.pb.meta.GetSchemasResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_GetSchemasResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_GetSchemasResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.meta.GetSchemasResponse.class, com.dingodb.pb.meta.GetSchemasResponse.Builder.class);
    }

    // Construct using com.dingodb.pb.meta.GetSchemasResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      if (schemasBuilder_ == null) {
        schemas_ = java.util.Collections.emptyList();
      } else {
        schemas_ = null;
        schemasBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_GetSchemasResponse_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.GetSchemasResponse getDefaultInstanceForType() {
      return com.dingodb.pb.meta.GetSchemasResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.meta.GetSchemasResponse build() {
      com.dingodb.pb.meta.GetSchemasResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.GetSchemasResponse buildPartial() {
      com.dingodb.pb.meta.GetSchemasResponse result = new com.dingodb.pb.meta.GetSchemasResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dingodb.pb.meta.GetSchemasResponse result) {
      if (schemasBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          schemas_ = java.util.Collections.unmodifiableList(schemas_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.schemas_ = schemas_;
      } else {
        result.schemas_ = schemasBuilder_.build();
      }
    }

    private void buildPartial0(com.dingodb.pb.meta.GetSchemasResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.meta.GetSchemasResponse) {
        return mergeFrom((com.dingodb.pb.meta.GetSchemasResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.meta.GetSchemasResponse other) {
      if (other == com.dingodb.pb.meta.GetSchemasResponse.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (schemasBuilder_ == null) {
        if (!other.schemas_.isEmpty()) {
          if (schemas_.isEmpty()) {
            schemas_ = other.schemas_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSchemasIsMutable();
            schemas_.addAll(other.schemas_);
          }
          onChanged();
        }
      } else {
        if (!other.schemas_.isEmpty()) {
          if (schemasBuilder_.isEmpty()) {
            schemasBuilder_.dispose();
            schemasBuilder_ = null;
            schemas_ = other.schemas_;
            bitField0_ = (bitField0_ & ~0x00000002);
            schemasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSchemasFieldBuilder() : null;
          } else {
            schemasBuilder_.addAllMessages(other.schemas_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.dingodb.pb.meta.Schema m =
                  input.readMessage(
                      com.dingodb.pb.meta.Schema.parser(),
                      extensionRegistry);
              if (schemasBuilder_ == null) {
                ensureSchemasIsMutable();
                schemas_.add(m);
              } else {
                schemasBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.dingodb.pb.error.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.error.Error, com.dingodb.pb.error.Error.Builder, com.dingodb.pb.error.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     * @return The error.
     */
    public com.dingodb.pb.error.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.dingodb.pb.error.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    public Builder setError(com.dingodb.pb.error.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    public Builder setError(
        com.dingodb.pb.error.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    public Builder mergeError(com.dingodb.pb.error.Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          error_ != null &&
          error_ != com.dingodb.pb.error.Error.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000001);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    public com.dingodb.pb.error.Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    public com.dingodb.pb.error.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.dingodb.pb.error.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.error.Error, com.dingodb.pb.error.Error.Builder, com.dingodb.pb.error.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.error.Error, com.dingodb.pb.error.Error.Builder, com.dingodb.pb.error.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.util.List<com.dingodb.pb.meta.Schema> schemas_ =
      java.util.Collections.emptyList();
    private void ensureSchemasIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        schemas_ = new java.util.ArrayList<com.dingodb.pb.meta.Schema>(schemas_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.meta.Schema, com.dingodb.pb.meta.Schema.Builder, com.dingodb.pb.meta.SchemaOrBuilder> schemasBuilder_;

    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public java.util.List<com.dingodb.pb.meta.Schema> getSchemasList() {
      if (schemasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(schemas_);
      } else {
        return schemasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public int getSchemasCount() {
      if (schemasBuilder_ == null) {
        return schemas_.size();
      } else {
        return schemasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public com.dingodb.pb.meta.Schema getSchemas(int index) {
      if (schemasBuilder_ == null) {
        return schemas_.get(index);
      } else {
        return schemasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder setSchemas(
        int index, com.dingodb.pb.meta.Schema value) {
      if (schemasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSchemasIsMutable();
        schemas_.set(index, value);
        onChanged();
      } else {
        schemasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder setSchemas(
        int index, com.dingodb.pb.meta.Schema.Builder builderForValue) {
      if (schemasBuilder_ == null) {
        ensureSchemasIsMutable();
        schemas_.set(index, builderForValue.build());
        onChanged();
      } else {
        schemasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder addSchemas(com.dingodb.pb.meta.Schema value) {
      if (schemasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSchemasIsMutable();
        schemas_.add(value);
        onChanged();
      } else {
        schemasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder addSchemas(
        int index, com.dingodb.pb.meta.Schema value) {
      if (schemasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSchemasIsMutable();
        schemas_.add(index, value);
        onChanged();
      } else {
        schemasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder addSchemas(
        com.dingodb.pb.meta.Schema.Builder builderForValue) {
      if (schemasBuilder_ == null) {
        ensureSchemasIsMutable();
        schemas_.add(builderForValue.build());
        onChanged();
      } else {
        schemasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder addSchemas(
        int index, com.dingodb.pb.meta.Schema.Builder builderForValue) {
      if (schemasBuilder_ == null) {
        ensureSchemasIsMutable();
        schemas_.add(index, builderForValue.build());
        onChanged();
      } else {
        schemasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder addAllSchemas(
        java.lang.Iterable<? extends com.dingodb.pb.meta.Schema> values) {
      if (schemasBuilder_ == null) {
        ensureSchemasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, schemas_);
        onChanged();
      } else {
        schemasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder clearSchemas() {
      if (schemasBuilder_ == null) {
        schemas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        schemasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public Builder removeSchemas(int index) {
      if (schemasBuilder_ == null) {
        ensureSchemasIsMutable();
        schemas_.remove(index);
        onChanged();
      } else {
        schemasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public com.dingodb.pb.meta.Schema.Builder getSchemasBuilder(
        int index) {
      return getSchemasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public com.dingodb.pb.meta.SchemaOrBuilder getSchemasOrBuilder(
        int index) {
      if (schemasBuilder_ == null) {
        return schemas_.get(index);  } else {
        return schemasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public java.util.List<? extends com.dingodb.pb.meta.SchemaOrBuilder> 
         getSchemasOrBuilderList() {
      if (schemasBuilder_ != null) {
        return schemasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(schemas_);
      }
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public com.dingodb.pb.meta.Schema.Builder addSchemasBuilder() {
      return getSchemasFieldBuilder().addBuilder(
          com.dingodb.pb.meta.Schema.getDefaultInstance());
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public com.dingodb.pb.meta.Schema.Builder addSchemasBuilder(
        int index) {
      return getSchemasFieldBuilder().addBuilder(
          index, com.dingodb.pb.meta.Schema.getDefaultInstance());
    }
    /**
     * <code>repeated .dingodb.pb.meta.Schema schemas = 2 [json_name = "schemas"];</code>
     */
    public java.util.List<com.dingodb.pb.meta.Schema.Builder> 
         getSchemasBuilderList() {
      return getSchemasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.meta.Schema, com.dingodb.pb.meta.Schema.Builder, com.dingodb.pb.meta.SchemaOrBuilder> 
        getSchemasFieldBuilder() {
      if (schemasBuilder_ == null) {
        schemasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dingodb.pb.meta.Schema, com.dingodb.pb.meta.Schema.Builder, com.dingodb.pb.meta.SchemaOrBuilder>(
                schemas_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        schemas_ = null;
      }
      return schemasBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.meta.GetSchemasResponse)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.meta.GetSchemasResponse)
  private static final com.dingodb.pb.meta.GetSchemasResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.meta.GetSchemasResponse();
  }

  public static com.dingodb.pb.meta.GetSchemasResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSchemasResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSchemasResponse>() {
    @java.lang.Override
    public GetSchemasResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSchemasResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSchemasResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.meta.GetSchemasResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

