// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

public interface GetTableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.meta.GetTableResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  com.dingodb.pb.error.Error getError();
  /**
   * <code>.dingodb.pb.error.Error error = 1 [json_name = "error"];</code>
   */
  com.dingodb.pb.error.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.dingodb.pb.meta.Table table = 2 [json_name = "table"];</code>
   * @return Whether the table field is set.
   */
  boolean hasTable();
  /**
   * <code>.dingodb.pb.meta.Table table = 2 [json_name = "table"];</code>
   * @return The table.
   */
  com.dingodb.pb.meta.Table getTable();
  /**
   * <code>.dingodb.pb.meta.Table table = 2 [json_name = "table"];</code>
   */
  com.dingodb.pb.meta.TableOrBuilder getTableOrBuilder();
}
