// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

public interface HashPartitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.meta.HashPartition)
    com.google.protobuf.MessageOrBuilder {
}
