// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

/**
 * <pre>
 * This Part is mainly equal to the Part in DingoDB 0.5.x
 * </pre>
 *
 * Protobuf type {@code dingodb.pb.meta.Part}
 */
public final class Part extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.meta.Part)
    PartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Part.newBuilder() to construct.
  private Part(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Part() {
    voters_ = java.util.Collections.emptyList();
    learners_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Part();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_Part_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_Part_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.meta.Part.class, com.dingodb.pb.meta.Part.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.dingodb.pb.meta.DingoCommonId id_;
  /**
   * <pre>
   * this is really region id, its parent entity is table
   * </pre>
   *
   * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <pre>
   * this is really region id, its parent entity is table
   * </pre>
   *
   * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonId getId() {
    return id_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : id_;
  }
  /**
   * <pre>
   * this is really region id, its parent entity is table
   * </pre>
   *
   * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.meta.DingoCommonIdOrBuilder getIdOrBuilder() {
    return id_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : id_;
  }

  public static final int RANGE_FIELD_NUMBER = 2;
  private com.dingodb.pb.common.Range range_;
  /**
   * <pre>
   * the range of this part
   * </pre>
   *
   * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
   * @return Whether the range field is set.
   */
  @java.lang.Override
  public boolean hasRange() {
    return range_ != null;
  }
  /**
   * <pre>
   * the range of this part
   * </pre>
   *
   * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
   * @return The range.
   */
  @java.lang.Override
  public com.dingodb.pb.common.Range getRange() {
    return range_ == null ? com.dingodb.pb.common.Range.getDefaultInstance() : range_;
  }
  /**
   * <pre>
   * the range of this part
   * </pre>
   *
   * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.RangeOrBuilder getRangeOrBuilder() {
    return range_ == null ? com.dingodb.pb.common.Range.getDefaultInstance() : range_;
  }

  public static final int LEADER_FIELD_NUMBER = 3;
  private com.dingodb.pb.common.Location leader_;
  /**
   * <pre>
   * the leader's store location
   * </pre>
   *
   * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
   * @return Whether the leader field is set.
   */
  @java.lang.Override
  public boolean hasLeader() {
    return leader_ != null;
  }
  /**
   * <pre>
   * the leader's store location
   * </pre>
   *
   * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
   * @return The leader.
   */
  @java.lang.Override
  public com.dingodb.pb.common.Location getLeader() {
    return leader_ == null ? com.dingodb.pb.common.Location.getDefaultInstance() : leader_;
  }
  /**
   * <pre>
   * the leader's store location
   * </pre>
   *
   * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.LocationOrBuilder getLeaderOrBuilder() {
    return leader_ == null ? com.dingodb.pb.common.Location.getDefaultInstance() : leader_;
  }

  public static final int VOTERS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.dingodb.pb.common.Location> voters_;
  /**
   * <pre>
   * all members of the region that have right to vote, this field is
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dingodb.pb.common.Location> getVotersList() {
    return voters_;
  }
  /**
   * <pre>
   * all members of the region that have right to vote, this field is
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dingodb.pb.common.LocationOrBuilder> 
      getVotersOrBuilderList() {
    return voters_;
  }
  /**
   * <pre>
   * all members of the region that have right to vote, this field is
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
   */
  @java.lang.Override
  public int getVotersCount() {
    return voters_.size();
  }
  /**
   * <pre>
   * all members of the region that have right to vote, this field is
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.Location getVoters(int index) {
    return voters_.get(index);
  }
  /**
   * <pre>
   * all members of the region that have right to vote, this field is
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.LocationOrBuilder getVotersOrBuilder(
      int index) {
    return voters_.get(index);
  }

  public static final int LEARNERS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.dingodb.pb.common.Location> learners_;
  /**
   * <pre>
   * equal to the old replicates field of Part.
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dingodb.pb.common.Location> getLearnersList() {
    return learners_;
  }
  /**
   * <pre>
   * equal to the old replicates field of Part.
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dingodb.pb.common.LocationOrBuilder> 
      getLearnersOrBuilderList() {
    return learners_;
  }
  /**
   * <pre>
   * equal to the old replicates field of Part.
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
   */
  @java.lang.Override
  public int getLearnersCount() {
    return learners_.size();
  }
  /**
   * <pre>
   * equal to the old replicates field of Part.
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.Location getLearners(int index) {
    return learners_.get(index);
  }
  /**
   * <pre>
   * equal to the old replicates field of Part.
   * </pre>
   *
   * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.LocationOrBuilder getLearnersOrBuilder(
      int index) {
    return learners_.get(index);
  }

  public static final int REGIONMAP_EPOCH_FIELD_NUMBER = 6;
  private long regionmapEpoch_ = 0L;
  /**
   * <code>uint64 regionmap_epoch = 6 [json_name = "regionmapEpoch"];</code>
   * @return The regionmapEpoch.
   */
  @java.lang.Override
  public long getRegionmapEpoch() {
    return regionmapEpoch_;
  }

  public static final int STOREMAP_EPOCH_FIELD_NUMBER = 7;
  private long storemapEpoch_ = 0L;
  /**
   * <code>uint64 storemap_epoch = 7 [json_name = "storemapEpoch"];</code>
   * @return The storemapEpoch.
   */
  @java.lang.Override
  public long getStoremapEpoch() {
    return storemapEpoch_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (range_ != null) {
      output.writeMessage(2, getRange());
    }
    if (leader_ != null) {
      output.writeMessage(3, getLeader());
    }
    for (int i = 0; i < voters_.size(); i++) {
      output.writeMessage(4, voters_.get(i));
    }
    for (int i = 0; i < learners_.size(); i++) {
      output.writeMessage(5, learners_.get(i));
    }
    if (regionmapEpoch_ != 0L) {
      output.writeUInt64(6, regionmapEpoch_);
    }
    if (storemapEpoch_ != 0L) {
      output.writeUInt64(7, storemapEpoch_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (range_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRange());
    }
    if (leader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLeader());
    }
    for (int i = 0; i < voters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, voters_.get(i));
    }
    for (int i = 0; i < learners_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, learners_.get(i));
    }
    if (regionmapEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, regionmapEpoch_);
    }
    if (storemapEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, storemapEpoch_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.meta.Part)) {
      return super.equals(obj);
    }
    com.dingodb.pb.meta.Part other = (com.dingodb.pb.meta.Part) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasRange() != other.hasRange()) return false;
    if (hasRange()) {
      if (!getRange()
          .equals(other.getRange())) return false;
    }
    if (hasLeader() != other.hasLeader()) return false;
    if (hasLeader()) {
      if (!getLeader()
          .equals(other.getLeader())) return false;
    }
    if (!getVotersList()
        .equals(other.getVotersList())) return false;
    if (!getLearnersList()
        .equals(other.getLearnersList())) return false;
    if (getRegionmapEpoch()
        != other.getRegionmapEpoch()) return false;
    if (getStoremapEpoch()
        != other.getStoremapEpoch()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasRange()) {
      hash = (37 * hash) + RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getRange().hashCode();
    }
    if (hasLeader()) {
      hash = (37 * hash) + LEADER_FIELD_NUMBER;
      hash = (53 * hash) + getLeader().hashCode();
    }
    if (getVotersCount() > 0) {
      hash = (37 * hash) + VOTERS_FIELD_NUMBER;
      hash = (53 * hash) + getVotersList().hashCode();
    }
    if (getLearnersCount() > 0) {
      hash = (37 * hash) + LEARNERS_FIELD_NUMBER;
      hash = (53 * hash) + getLearnersList().hashCode();
    }
    hash = (37 * hash) + REGIONMAP_EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRegionmapEpoch());
    hash = (37 * hash) + STOREMAP_EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStoremapEpoch());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.meta.Part parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.Part parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.Part parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.Part parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.Part parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.Part parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.meta.Part prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * This Part is mainly equal to the Part in DingoDB 0.5.x
   * </pre>
   *
   * Protobuf type {@code dingodb.pb.meta.Part}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.meta.Part)
      com.dingodb.pb.meta.PartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_Part_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_Part_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.meta.Part.class, com.dingodb.pb.meta.Part.Builder.class);
    }

    // Construct using com.dingodb.pb.meta.Part.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      range_ = null;
      if (rangeBuilder_ != null) {
        rangeBuilder_.dispose();
        rangeBuilder_ = null;
      }
      leader_ = null;
      if (leaderBuilder_ != null) {
        leaderBuilder_.dispose();
        leaderBuilder_ = null;
      }
      if (votersBuilder_ == null) {
        voters_ = java.util.Collections.emptyList();
      } else {
        voters_ = null;
        votersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (learnersBuilder_ == null) {
        learners_ = java.util.Collections.emptyList();
      } else {
        learners_ = null;
        learnersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      regionmapEpoch_ = 0L;
      storemapEpoch_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_Part_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.Part getDefaultInstanceForType() {
      return com.dingodb.pb.meta.Part.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.meta.Part build() {
      com.dingodb.pb.meta.Part result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.Part buildPartial() {
      com.dingodb.pb.meta.Part result = new com.dingodb.pb.meta.Part(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dingodb.pb.meta.Part result) {
      if (votersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          voters_ = java.util.Collections.unmodifiableList(voters_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.voters_ = voters_;
      } else {
        result.voters_ = votersBuilder_.build();
      }
      if (learnersBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          learners_ = java.util.Collections.unmodifiableList(learners_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.learners_ = learners_;
      } else {
        result.learners_ = learnersBuilder_.build();
      }
    }

    private void buildPartial0(com.dingodb.pb.meta.Part result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.range_ = rangeBuilder_ == null
            ? range_
            : rangeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.leader_ = leaderBuilder_ == null
            ? leader_
            : leaderBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.regionmapEpoch_ = regionmapEpoch_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.storemapEpoch_ = storemapEpoch_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.meta.Part) {
        return mergeFrom((com.dingodb.pb.meta.Part)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.meta.Part other) {
      if (other == com.dingodb.pb.meta.Part.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasRange()) {
        mergeRange(other.getRange());
      }
      if (other.hasLeader()) {
        mergeLeader(other.getLeader());
      }
      if (votersBuilder_ == null) {
        if (!other.voters_.isEmpty()) {
          if (voters_.isEmpty()) {
            voters_ = other.voters_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureVotersIsMutable();
            voters_.addAll(other.voters_);
          }
          onChanged();
        }
      } else {
        if (!other.voters_.isEmpty()) {
          if (votersBuilder_.isEmpty()) {
            votersBuilder_.dispose();
            votersBuilder_ = null;
            voters_ = other.voters_;
            bitField0_ = (bitField0_ & ~0x00000008);
            votersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVotersFieldBuilder() : null;
          } else {
            votersBuilder_.addAllMessages(other.voters_);
          }
        }
      }
      if (learnersBuilder_ == null) {
        if (!other.learners_.isEmpty()) {
          if (learners_.isEmpty()) {
            learners_ = other.learners_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureLearnersIsMutable();
            learners_.addAll(other.learners_);
          }
          onChanged();
        }
      } else {
        if (!other.learners_.isEmpty()) {
          if (learnersBuilder_.isEmpty()) {
            learnersBuilder_.dispose();
            learnersBuilder_ = null;
            learners_ = other.learners_;
            bitField0_ = (bitField0_ & ~0x00000010);
            learnersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLearnersFieldBuilder() : null;
          } else {
            learnersBuilder_.addAllMessages(other.learners_);
          }
        }
      }
      if (other.getRegionmapEpoch() != 0L) {
        setRegionmapEpoch(other.getRegionmapEpoch());
      }
      if (other.getStoremapEpoch() != 0L) {
        setStoremapEpoch(other.getStoremapEpoch());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getLeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.dingodb.pb.common.Location m =
                  input.readMessage(
                      com.dingodb.pb.common.Location.parser(),
                      extensionRegistry);
              if (votersBuilder_ == null) {
                ensureVotersIsMutable();
                voters_.add(m);
              } else {
                votersBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              com.dingodb.pb.common.Location m =
                  input.readMessage(
                      com.dingodb.pb.common.Location.parser(),
                      extensionRegistry);
              if (learnersBuilder_ == null) {
                ensureLearnersIsMutable();
                learners_.add(m);
              } else {
                learnersBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 48: {
              regionmapEpoch_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              storemapEpoch_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.dingodb.pb.meta.DingoCommonId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder> idBuilder_;
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public com.dingodb.pb.meta.DingoCommonId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    public Builder setId(com.dingodb.pb.meta.DingoCommonId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    public Builder setId(
        com.dingodb.pb.meta.DingoCommonId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    public Builder mergeId(com.dingodb.pb.meta.DingoCommonId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          id_ != null &&
          id_ != com.dingodb.pb.meta.DingoCommonId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    public com.dingodb.pb.meta.DingoCommonId.Builder getIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    public com.dingodb.pb.meta.DingoCommonIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.dingodb.pb.meta.DingoCommonId.getDefaultInstance() : id_;
      }
    }
    /**
     * <pre>
     * this is really region id, its parent entity is table
     * </pre>
     *
     * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.meta.DingoCommonId, com.dingodb.pb.meta.DingoCommonId.Builder, com.dingodb.pb.meta.DingoCommonIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.dingodb.pb.common.Range range_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.common.Range, com.dingodb.pb.common.Range.Builder, com.dingodb.pb.common.RangeOrBuilder> rangeBuilder_;
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     * @return Whether the range field is set.
     */
    public boolean hasRange() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     * @return The range.
     */
    public com.dingodb.pb.common.Range getRange() {
      if (rangeBuilder_ == null) {
        return range_ == null ? com.dingodb.pb.common.Range.getDefaultInstance() : range_;
      } else {
        return rangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    public Builder setRange(com.dingodb.pb.common.Range value) {
      if (rangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        range_ = value;
      } else {
        rangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    public Builder setRange(
        com.dingodb.pb.common.Range.Builder builderForValue) {
      if (rangeBuilder_ == null) {
        range_ = builderForValue.build();
      } else {
        rangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    public Builder mergeRange(com.dingodb.pb.common.Range value) {
      if (rangeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          range_ != null &&
          range_ != com.dingodb.pb.common.Range.getDefaultInstance()) {
          getRangeBuilder().mergeFrom(value);
        } else {
          range_ = value;
        }
      } else {
        rangeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    public Builder clearRange() {
      bitField0_ = (bitField0_ & ~0x00000002);
      range_ = null;
      if (rangeBuilder_ != null) {
        rangeBuilder_.dispose();
        rangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    public com.dingodb.pb.common.Range.Builder getRangeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    public com.dingodb.pb.common.RangeOrBuilder getRangeOrBuilder() {
      if (rangeBuilder_ != null) {
        return rangeBuilder_.getMessageOrBuilder();
      } else {
        return range_ == null ?
            com.dingodb.pb.common.Range.getDefaultInstance() : range_;
      }
    }
    /**
     * <pre>
     * the range of this part
     * </pre>
     *
     * <code>.dingodb.pb.common.Range range = 2 [json_name = "range"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.common.Range, com.dingodb.pb.common.Range.Builder, com.dingodb.pb.common.RangeOrBuilder> 
        getRangeFieldBuilder() {
      if (rangeBuilder_ == null) {
        rangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.common.Range, com.dingodb.pb.common.Range.Builder, com.dingodb.pb.common.RangeOrBuilder>(
                getRange(),
                getParentForChildren(),
                isClean());
        range_ = null;
      }
      return rangeBuilder_;
    }

    private com.dingodb.pb.common.Location leader_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder> leaderBuilder_;
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     * @return Whether the leader field is set.
     */
    public boolean hasLeader() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     * @return The leader.
     */
    public com.dingodb.pb.common.Location getLeader() {
      if (leaderBuilder_ == null) {
        return leader_ == null ? com.dingodb.pb.common.Location.getDefaultInstance() : leader_;
      } else {
        return leaderBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    public Builder setLeader(com.dingodb.pb.common.Location value) {
      if (leaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leader_ = value;
      } else {
        leaderBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    public Builder setLeader(
        com.dingodb.pb.common.Location.Builder builderForValue) {
      if (leaderBuilder_ == null) {
        leader_ = builderForValue.build();
      } else {
        leaderBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    public Builder mergeLeader(com.dingodb.pb.common.Location value) {
      if (leaderBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          leader_ != null &&
          leader_ != com.dingodb.pb.common.Location.getDefaultInstance()) {
          getLeaderBuilder().mergeFrom(value);
        } else {
          leader_ = value;
        }
      } else {
        leaderBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    public Builder clearLeader() {
      bitField0_ = (bitField0_ & ~0x00000004);
      leader_ = null;
      if (leaderBuilder_ != null) {
        leaderBuilder_.dispose();
        leaderBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    public com.dingodb.pb.common.Location.Builder getLeaderBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getLeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    public com.dingodb.pb.common.LocationOrBuilder getLeaderOrBuilder() {
      if (leaderBuilder_ != null) {
        return leaderBuilder_.getMessageOrBuilder();
      } else {
        return leader_ == null ?
            com.dingodb.pb.common.Location.getDefaultInstance() : leader_;
      }
    }
    /**
     * <pre>
     * the leader's store location
     * </pre>
     *
     * <code>.dingodb.pb.common.Location leader = 3 [json_name = "leader"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder> 
        getLeaderFieldBuilder() {
      if (leaderBuilder_ == null) {
        leaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder>(
                getLeader(),
                getParentForChildren(),
                isClean());
        leader_ = null;
      }
      return leaderBuilder_;
    }

    private java.util.List<com.dingodb.pb.common.Location> voters_ =
      java.util.Collections.emptyList();
    private void ensureVotersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        voters_ = new java.util.ArrayList<com.dingodb.pb.common.Location>(voters_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder> votersBuilder_;

    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public java.util.List<com.dingodb.pb.common.Location> getVotersList() {
      if (votersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(voters_);
      } else {
        return votersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public int getVotersCount() {
      if (votersBuilder_ == null) {
        return voters_.size();
      } else {
        return votersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public com.dingodb.pb.common.Location getVoters(int index) {
      if (votersBuilder_ == null) {
        return voters_.get(index);
      } else {
        return votersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder setVoters(
        int index, com.dingodb.pb.common.Location value) {
      if (votersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVotersIsMutable();
        voters_.set(index, value);
        onChanged();
      } else {
        votersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder setVoters(
        int index, com.dingodb.pb.common.Location.Builder builderForValue) {
      if (votersBuilder_ == null) {
        ensureVotersIsMutable();
        voters_.set(index, builderForValue.build());
        onChanged();
      } else {
        votersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder addVoters(com.dingodb.pb.common.Location value) {
      if (votersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVotersIsMutable();
        voters_.add(value);
        onChanged();
      } else {
        votersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder addVoters(
        int index, com.dingodb.pb.common.Location value) {
      if (votersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVotersIsMutable();
        voters_.add(index, value);
        onChanged();
      } else {
        votersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder addVoters(
        com.dingodb.pb.common.Location.Builder builderForValue) {
      if (votersBuilder_ == null) {
        ensureVotersIsMutable();
        voters_.add(builderForValue.build());
        onChanged();
      } else {
        votersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder addVoters(
        int index, com.dingodb.pb.common.Location.Builder builderForValue) {
      if (votersBuilder_ == null) {
        ensureVotersIsMutable();
        voters_.add(index, builderForValue.build());
        onChanged();
      } else {
        votersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder addAllVoters(
        java.lang.Iterable<? extends com.dingodb.pb.common.Location> values) {
      if (votersBuilder_ == null) {
        ensureVotersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, voters_);
        onChanged();
      } else {
        votersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder clearVoters() {
      if (votersBuilder_ == null) {
        voters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        votersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public Builder removeVoters(int index) {
      if (votersBuilder_ == null) {
        ensureVotersIsMutable();
        voters_.remove(index);
        onChanged();
      } else {
        votersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public com.dingodb.pb.common.Location.Builder getVotersBuilder(
        int index) {
      return getVotersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public com.dingodb.pb.common.LocationOrBuilder getVotersOrBuilder(
        int index) {
      if (votersBuilder_ == null) {
        return voters_.get(index);  } else {
        return votersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public java.util.List<? extends com.dingodb.pb.common.LocationOrBuilder> 
         getVotersOrBuilderList() {
      if (votersBuilder_ != null) {
        return votersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(voters_);
      }
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public com.dingodb.pb.common.Location.Builder addVotersBuilder() {
      return getVotersFieldBuilder().addBuilder(
          com.dingodb.pb.common.Location.getDefaultInstance());
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public com.dingodb.pb.common.Location.Builder addVotersBuilder(
        int index) {
      return getVotersFieldBuilder().addBuilder(
          index, com.dingodb.pb.common.Location.getDefaultInstance());
    }
    /**
     * <pre>
     * all members of the region that have right to vote, this field is
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location voters = 4 [json_name = "voters"];</code>
     */
    public java.util.List<com.dingodb.pb.common.Location.Builder> 
         getVotersBuilderList() {
      return getVotersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder> 
        getVotersFieldBuilder() {
      if (votersBuilder_ == null) {
        votersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder>(
                voters_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        voters_ = null;
      }
      return votersBuilder_;
    }

    private java.util.List<com.dingodb.pb.common.Location> learners_ =
      java.util.Collections.emptyList();
    private void ensureLearnersIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        learners_ = new java.util.ArrayList<com.dingodb.pb.common.Location>(learners_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder> learnersBuilder_;

    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public java.util.List<com.dingodb.pb.common.Location> getLearnersList() {
      if (learnersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(learners_);
      } else {
        return learnersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public int getLearnersCount() {
      if (learnersBuilder_ == null) {
        return learners_.size();
      } else {
        return learnersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public com.dingodb.pb.common.Location getLearners(int index) {
      if (learnersBuilder_ == null) {
        return learners_.get(index);
      } else {
        return learnersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder setLearners(
        int index, com.dingodb.pb.common.Location value) {
      if (learnersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLearnersIsMutable();
        learners_.set(index, value);
        onChanged();
      } else {
        learnersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder setLearners(
        int index, com.dingodb.pb.common.Location.Builder builderForValue) {
      if (learnersBuilder_ == null) {
        ensureLearnersIsMutable();
        learners_.set(index, builderForValue.build());
        onChanged();
      } else {
        learnersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder addLearners(com.dingodb.pb.common.Location value) {
      if (learnersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLearnersIsMutable();
        learners_.add(value);
        onChanged();
      } else {
        learnersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder addLearners(
        int index, com.dingodb.pb.common.Location value) {
      if (learnersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLearnersIsMutable();
        learners_.add(index, value);
        onChanged();
      } else {
        learnersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder addLearners(
        com.dingodb.pb.common.Location.Builder builderForValue) {
      if (learnersBuilder_ == null) {
        ensureLearnersIsMutable();
        learners_.add(builderForValue.build());
        onChanged();
      } else {
        learnersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder addLearners(
        int index, com.dingodb.pb.common.Location.Builder builderForValue) {
      if (learnersBuilder_ == null) {
        ensureLearnersIsMutable();
        learners_.add(index, builderForValue.build());
        onChanged();
      } else {
        learnersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder addAllLearners(
        java.lang.Iterable<? extends com.dingodb.pb.common.Location> values) {
      if (learnersBuilder_ == null) {
        ensureLearnersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, learners_);
        onChanged();
      } else {
        learnersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder clearLearners() {
      if (learnersBuilder_ == null) {
        learners_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        learnersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public Builder removeLearners(int index) {
      if (learnersBuilder_ == null) {
        ensureLearnersIsMutable();
        learners_.remove(index);
        onChanged();
      } else {
        learnersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public com.dingodb.pb.common.Location.Builder getLearnersBuilder(
        int index) {
      return getLearnersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public com.dingodb.pb.common.LocationOrBuilder getLearnersOrBuilder(
        int index) {
      if (learnersBuilder_ == null) {
        return learners_.get(index);  } else {
        return learnersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public java.util.List<? extends com.dingodb.pb.common.LocationOrBuilder> 
         getLearnersOrBuilderList() {
      if (learnersBuilder_ != null) {
        return learnersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(learners_);
      }
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public com.dingodb.pb.common.Location.Builder addLearnersBuilder() {
      return getLearnersFieldBuilder().addBuilder(
          com.dingodb.pb.common.Location.getDefaultInstance());
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public com.dingodb.pb.common.Location.Builder addLearnersBuilder(
        int index) {
      return getLearnersFieldBuilder().addBuilder(
          index, com.dingodb.pb.common.Location.getDefaultInstance());
    }
    /**
     * <pre>
     * equal to the old replicates field of Part.
     * </pre>
     *
     * <code>repeated .dingodb.pb.common.Location learners = 5 [json_name = "learners"];</code>
     */
    public java.util.List<com.dingodb.pb.common.Location.Builder> 
         getLearnersBuilderList() {
      return getLearnersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder> 
        getLearnersFieldBuilder() {
      if (learnersBuilder_ == null) {
        learnersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dingodb.pb.common.Location, com.dingodb.pb.common.Location.Builder, com.dingodb.pb.common.LocationOrBuilder>(
                learners_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        learners_ = null;
      }
      return learnersBuilder_;
    }

    private long regionmapEpoch_ ;
    /**
     * <code>uint64 regionmap_epoch = 6 [json_name = "regionmapEpoch"];</code>
     * @return The regionmapEpoch.
     */
    @java.lang.Override
    public long getRegionmapEpoch() {
      return regionmapEpoch_;
    }
    /**
     * <code>uint64 regionmap_epoch = 6 [json_name = "regionmapEpoch"];</code>
     * @param value The regionmapEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setRegionmapEpoch(long value) {

      regionmapEpoch_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 regionmap_epoch = 6 [json_name = "regionmapEpoch"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRegionmapEpoch() {
      bitField0_ = (bitField0_ & ~0x00000020);
      regionmapEpoch_ = 0L;
      onChanged();
      return this;
    }

    private long storemapEpoch_ ;
    /**
     * <code>uint64 storemap_epoch = 7 [json_name = "storemapEpoch"];</code>
     * @return The storemapEpoch.
     */
    @java.lang.Override
    public long getStoremapEpoch() {
      return storemapEpoch_;
    }
    /**
     * <code>uint64 storemap_epoch = 7 [json_name = "storemapEpoch"];</code>
     * @param value The storemapEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setStoremapEpoch(long value) {

      storemapEpoch_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 storemap_epoch = 7 [json_name = "storemapEpoch"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStoremapEpoch() {
      bitField0_ = (bitField0_ & ~0x00000040);
      storemapEpoch_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.meta.Part)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.meta.Part)
  private static final com.dingodb.pb.meta.Part DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.meta.Part();
  }

  public static com.dingodb.pb.meta.Part getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Part>
      PARSER = new com.google.protobuf.AbstractParser<Part>() {
    @java.lang.Override
    public Part parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Part> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Part> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.meta.Part getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

