// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

/**
 * Protobuf type {@code dingodb.pb.meta.RangePartition}
 */
public final class RangePartition extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.meta.RangePartition)
    RangePartitionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RangePartition.newBuilder() to construct.
  private RangePartition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RangePartition() {
    ranges_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RangePartition();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_RangePartition_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_RangePartition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.meta.RangePartition.class, com.dingodb.pb.meta.RangePartition.Builder.class);
  }

  public static final int RANGES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.dingodb.pb.common.Range> ranges_;
  /**
   * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dingodb.pb.common.Range> getRangesList() {
    return ranges_;
  }
  /**
   * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dingodb.pb.common.RangeOrBuilder> 
      getRangesOrBuilderList() {
    return ranges_;
  }
  /**
   * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
   */
  @java.lang.Override
  public int getRangesCount() {
    return ranges_.size();
  }
  /**
   * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.Range getRanges(int index) {
    return ranges_.get(index);
  }
  /**
   * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
   */
  @java.lang.Override
  public com.dingodb.pb.common.RangeOrBuilder getRangesOrBuilder(
      int index) {
    return ranges_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ranges_.size(); i++) {
      output.writeMessage(1, ranges_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ranges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ranges_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.meta.RangePartition)) {
      return super.equals(obj);
    }
    com.dingodb.pb.meta.RangePartition other = (com.dingodb.pb.meta.RangePartition) obj;

    if (!getRangesList()
        .equals(other.getRangesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRangesCount() > 0) {
      hash = (37 * hash) + RANGES_FIELD_NUMBER;
      hash = (53 * hash) + getRangesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.meta.RangePartition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.RangePartition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.RangePartition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.meta.RangePartition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.meta.RangePartition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dingodb.pb.meta.RangePartition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.meta.RangePartition)
      com.dingodb.pb.meta.RangePartitionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_RangePartition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_RangePartition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.meta.RangePartition.class, com.dingodb.pb.meta.RangePartition.Builder.class);
    }

    // Construct using com.dingodb.pb.meta.RangePartition.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (rangesBuilder_ == null) {
        ranges_ = java.util.Collections.emptyList();
      } else {
        ranges_ = null;
        rangesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.meta.MetaProto.internal_static_dingodb_pb_meta_RangePartition_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.RangePartition getDefaultInstanceForType() {
      return com.dingodb.pb.meta.RangePartition.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.meta.RangePartition build() {
      com.dingodb.pb.meta.RangePartition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.meta.RangePartition buildPartial() {
      com.dingodb.pb.meta.RangePartition result = new com.dingodb.pb.meta.RangePartition(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dingodb.pb.meta.RangePartition result) {
      if (rangesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ranges_ = java.util.Collections.unmodifiableList(ranges_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ranges_ = ranges_;
      } else {
        result.ranges_ = rangesBuilder_.build();
      }
    }

    private void buildPartial0(com.dingodb.pb.meta.RangePartition result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.meta.RangePartition) {
        return mergeFrom((com.dingodb.pb.meta.RangePartition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.meta.RangePartition other) {
      if (other == com.dingodb.pb.meta.RangePartition.getDefaultInstance()) return this;
      if (rangesBuilder_ == null) {
        if (!other.ranges_.isEmpty()) {
          if (ranges_.isEmpty()) {
            ranges_ = other.ranges_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRangesIsMutable();
            ranges_.addAll(other.ranges_);
          }
          onChanged();
        }
      } else {
        if (!other.ranges_.isEmpty()) {
          if (rangesBuilder_.isEmpty()) {
            rangesBuilder_.dispose();
            rangesBuilder_ = null;
            ranges_ = other.ranges_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rangesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRangesFieldBuilder() : null;
          } else {
            rangesBuilder_.addAllMessages(other.ranges_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.dingodb.pb.common.Range m =
                  input.readMessage(
                      com.dingodb.pb.common.Range.parser(),
                      extensionRegistry);
              if (rangesBuilder_ == null) {
                ensureRangesIsMutable();
                ranges_.add(m);
              } else {
                rangesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.dingodb.pb.common.Range> ranges_ =
      java.util.Collections.emptyList();
    private void ensureRangesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ranges_ = new java.util.ArrayList<com.dingodb.pb.common.Range>(ranges_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.common.Range, com.dingodb.pb.common.Range.Builder, com.dingodb.pb.common.RangeOrBuilder> rangesBuilder_;

    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public java.util.List<com.dingodb.pb.common.Range> getRangesList() {
      if (rangesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ranges_);
      } else {
        return rangesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public int getRangesCount() {
      if (rangesBuilder_ == null) {
        return ranges_.size();
      } else {
        return rangesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public com.dingodb.pb.common.Range getRanges(int index) {
      if (rangesBuilder_ == null) {
        return ranges_.get(index);
      } else {
        return rangesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder setRanges(
        int index, com.dingodb.pb.common.Range value) {
      if (rangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRangesIsMutable();
        ranges_.set(index, value);
        onChanged();
      } else {
        rangesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder setRanges(
        int index, com.dingodb.pb.common.Range.Builder builderForValue) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.set(index, builderForValue.build());
        onChanged();
      } else {
        rangesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder addRanges(com.dingodb.pb.common.Range value) {
      if (rangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRangesIsMutable();
        ranges_.add(value);
        onChanged();
      } else {
        rangesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder addRanges(
        int index, com.dingodb.pb.common.Range value) {
      if (rangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRangesIsMutable();
        ranges_.add(index, value);
        onChanged();
      } else {
        rangesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder addRanges(
        com.dingodb.pb.common.Range.Builder builderForValue) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.add(builderForValue.build());
        onChanged();
      } else {
        rangesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder addRanges(
        int index, com.dingodb.pb.common.Range.Builder builderForValue) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.add(index, builderForValue.build());
        onChanged();
      } else {
        rangesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder addAllRanges(
        java.lang.Iterable<? extends com.dingodb.pb.common.Range> values) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ranges_);
        onChanged();
      } else {
        rangesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder clearRanges() {
      if (rangesBuilder_ == null) {
        ranges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rangesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public Builder removeRanges(int index) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.remove(index);
        onChanged();
      } else {
        rangesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public com.dingodb.pb.common.Range.Builder getRangesBuilder(
        int index) {
      return getRangesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public com.dingodb.pb.common.RangeOrBuilder getRangesOrBuilder(
        int index) {
      if (rangesBuilder_ == null) {
        return ranges_.get(index);  } else {
        return rangesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public java.util.List<? extends com.dingodb.pb.common.RangeOrBuilder> 
         getRangesOrBuilderList() {
      if (rangesBuilder_ != null) {
        return rangesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ranges_);
      }
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public com.dingodb.pb.common.Range.Builder addRangesBuilder() {
      return getRangesFieldBuilder().addBuilder(
          com.dingodb.pb.common.Range.getDefaultInstance());
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public com.dingodb.pb.common.Range.Builder addRangesBuilder(
        int index) {
      return getRangesFieldBuilder().addBuilder(
          index, com.dingodb.pb.common.Range.getDefaultInstance());
    }
    /**
     * <code>repeated .dingodb.pb.common.Range ranges = 1 [json_name = "ranges"];</code>
     */
    public java.util.List<com.dingodb.pb.common.Range.Builder> 
         getRangesBuilderList() {
      return getRangesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dingodb.pb.common.Range, com.dingodb.pb.common.Range.Builder, com.dingodb.pb.common.RangeOrBuilder> 
        getRangesFieldBuilder() {
      if (rangesBuilder_ == null) {
        rangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dingodb.pb.common.Range, com.dingodb.pb.common.Range.Builder, com.dingodb.pb.common.RangeOrBuilder>(
                ranges_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ranges_ = null;
      }
      return rangesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.meta.RangePartition)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.meta.RangePartition)
  private static final com.dingodb.pb.meta.RangePartition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.meta.RangePartition();
  }

  public static com.dingodb.pb.meta.RangePartition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RangePartition>
      PARSER = new com.google.protobuf.AbstractParser<RangePartition>() {
    @java.lang.Override
    public RangePartition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RangePartition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RangePartition> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.meta.RangePartition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

