// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

public interface TableDefinitionWithIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.meta.TableDefinitionWithId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.meta.DingoCommonId table_id = 1 [json_name = "tableId"];</code>
   * @return Whether the tableId field is set.
   */
  boolean hasTableId();
  /**
   * <code>.dingodb.pb.meta.DingoCommonId table_id = 1 [json_name = "tableId"];</code>
   * @return The tableId.
   */
  com.dingodb.pb.meta.DingoCommonId getTableId();
  /**
   * <code>.dingodb.pb.meta.DingoCommonId table_id = 1 [json_name = "tableId"];</code>
   */
  com.dingodb.pb.meta.DingoCommonIdOrBuilder getTableIdOrBuilder();

  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   * @return Whether the tableDefinition field is set.
   */
  boolean hasTableDefinition();
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   * @return The tableDefinition.
   */
  com.dingodb.pb.meta.TableDefinition getTableDefinition();
  /**
   * <code>.dingodb.pb.meta.TableDefinition table_definition = 2 [json_name = "tableDefinition"];</code>
   */
  com.dingodb.pb.meta.TableDefinitionOrBuilder getTableDefinitionOrBuilder();
}
