// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.dingodb.pb.meta;

public interface TableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dingodb.pb.meta.Table)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  com.dingodb.pb.meta.DingoCommonId getId();
  /**
   * <code>.dingodb.pb.meta.DingoCommonId id = 1 [json_name = "id"];</code>
   */
  com.dingodb.pb.meta.DingoCommonIdOrBuilder getIdOrBuilder();

  /**
   * <code>repeated .dingodb.pb.meta.Part parts = 2 [json_name = "parts"];</code>
   */
  java.util.List<com.dingodb.pb.meta.Part> 
      getPartsList();
  /**
   * <code>repeated .dingodb.pb.meta.Part parts = 2 [json_name = "parts"];</code>
   */
  com.dingodb.pb.meta.Part getParts(int index);
  /**
   * <code>repeated .dingodb.pb.meta.Part parts = 2 [json_name = "parts"];</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .dingodb.pb.meta.Part parts = 2 [json_name = "parts"];</code>
   */
  java.util.List<? extends com.dingodb.pb.meta.PartOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .dingodb.pb.meta.Part parts = 2 [json_name = "parts"];</code>
   */
  com.dingodb.pb.meta.PartOrBuilder getPartsOrBuilder(
      int index);
}
