// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package com.dingodb.pb.error;

/**
 * Protobuf type {@code dingodb.pb.error.Error}
 */
public final class Error extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dingodb.pb.error.Error)
    ErrorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Error.newBuilder() to construct.
  private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Error() {
    errcode_ = 0;
    errmsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Error();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dingodb.pb.error.ErrorProto.internal_static_dingodb_pb_error_Error_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dingodb.pb.error.ErrorProto.internal_static_dingodb_pb_error_Error_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dingodb.pb.error.Error.class, com.dingodb.pb.error.Error.Builder.class);
  }

  public static final int ERRCODE_FIELD_NUMBER = 1;
  private int errcode_ = 0;
  /**
   * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
   * @return The enum numeric value on the wire for errcode.
   */
  @java.lang.Override public int getErrcodeValue() {
    return errcode_;
  }
  /**
   * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
   * @return The errcode.
   */
  @java.lang.Override public com.dingodb.pb.error.Errno getErrcode() {
    com.dingodb.pb.error.Errno result = com.dingodb.pb.error.Errno.forNumber(errcode_);
    return result == null ? com.dingodb.pb.error.Errno.UNRECOGNIZED : result;
  }

  public static final int ERRMSG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errmsg_ = "";
  /**
   * <code>string errmsg = 2 [json_name = "errmsg"];</code>
   * @return The errmsg.
   */
  @java.lang.Override
  public java.lang.String getErrmsg() {
    java.lang.Object ref = errmsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errmsg_ = s;
      return s;
    }
  }
  /**
   * <code>string errmsg = 2 [json_name = "errmsg"];</code>
   * @return The bytes for errmsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrmsgBytes() {
    java.lang.Object ref = errmsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errmsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errcode_ != com.dingodb.pb.error.Errno.OK.getNumber()) {
      output.writeEnum(1, errcode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errmsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errmsg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errcode_ != com.dingodb.pb.error.Errno.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errcode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errmsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errmsg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dingodb.pb.error.Error)) {
      return super.equals(obj);
    }
    com.dingodb.pb.error.Error other = (com.dingodb.pb.error.Error) obj;

    if (errcode_ != other.errcode_) return false;
    if (!getErrmsg()
        .equals(other.getErrmsg())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
    hash = (53 * hash) + errcode_;
    hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrmsg().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dingodb.pb.error.Error parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.error.Error parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dingodb.pb.error.Error parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.error.Error parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.error.Error parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dingodb.pb.error.Error parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dingodb.pb.error.Error prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dingodb.pb.error.Error}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dingodb.pb.error.Error)
      com.dingodb.pb.error.ErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dingodb.pb.error.ErrorProto.internal_static_dingodb_pb_error_Error_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dingodb.pb.error.ErrorProto.internal_static_dingodb_pb_error_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dingodb.pb.error.Error.class, com.dingodb.pb.error.Error.Builder.class);
    }

    // Construct using com.dingodb.pb.error.Error.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      errcode_ = 0;
      errmsg_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dingodb.pb.error.ErrorProto.internal_static_dingodb_pb_error_Error_descriptor;
    }

    @java.lang.Override
    public com.dingodb.pb.error.Error getDefaultInstanceForType() {
      return com.dingodb.pb.error.Error.getDefaultInstance();
    }

    @java.lang.Override
    public com.dingodb.pb.error.Error build() {
      com.dingodb.pb.error.Error result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dingodb.pb.error.Error buildPartial() {
      com.dingodb.pb.error.Error result = new com.dingodb.pb.error.Error(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dingodb.pb.error.Error result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.errcode_ = errcode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.errmsg_ = errmsg_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dingodb.pb.error.Error) {
        return mergeFrom((com.dingodb.pb.error.Error)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dingodb.pb.error.Error other) {
      if (other == com.dingodb.pb.error.Error.getDefaultInstance()) return this;
      if (other.errcode_ != 0) {
        setErrcodeValue(other.getErrcodeValue());
      }
      if (!other.getErrmsg().isEmpty()) {
        errmsg_ = other.errmsg_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              errcode_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              errmsg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int errcode_ = 0;
    /**
     * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
     * @return The enum numeric value on the wire for errcode.
     */
    @java.lang.Override public int getErrcodeValue() {
      return errcode_;
    }
    /**
     * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
     * @param value The enum numeric value on the wire for errcode to set.
     * @return This builder for chaining.
     */
    public Builder setErrcodeValue(int value) {
      errcode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
     * @return The errcode.
     */
    @java.lang.Override
    public com.dingodb.pb.error.Errno getErrcode() {
      com.dingodb.pb.error.Errno result = com.dingodb.pb.error.Errno.forNumber(errcode_);
      return result == null ? com.dingodb.pb.error.Errno.UNRECOGNIZED : result;
    }
    /**
     * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
     * @param value The errcode to set.
     * @return This builder for chaining.
     */
    public Builder setErrcode(com.dingodb.pb.error.Errno value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      errcode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dingodb.pb.error.Errno errcode = 1 [json_name = "errcode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrcode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errcode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errmsg_ = "";
    /**
     * <code>string errmsg = 2 [json_name = "errmsg"];</code>
     * @return The errmsg.
     */
    public java.lang.String getErrmsg() {
      java.lang.Object ref = errmsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errmsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errmsg = 2 [json_name = "errmsg"];</code>
     * @return The bytes for errmsg.
     */
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errmsg = 2 [json_name = "errmsg"];</code>
     * @param value The errmsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrmsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errmsg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string errmsg = 2 [json_name = "errmsg"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrmsg() {
      errmsg_ = getDefaultInstance().getErrmsg();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string errmsg = 2 [json_name = "errmsg"];</code>
     * @param value The bytes for errmsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrmsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errmsg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dingodb.pb.error.Error)
  }

  // @@protoc_insertion_point(class_scope:dingodb.pb.error.Error)
  private static final com.dingodb.pb.error.Error DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dingodb.pb.error.Error();
  }

  public static com.dingodb.pb.error.Error getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Error>
      PARSER = new com.google.protobuf.AbstractParser<Error>() {
    @java.lang.Override
    public Error parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Error> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Error> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dingodb.pb.error.Error getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

